spring:
  jpa: 
    open-in-view: false
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password:
  driverClassName: org.h2.Driver

jwt:
  secret: farmfolio-secret-jwt-authentication-key
